<a href="https://colab.research.google.com/github/25ds3000042/Generative-Models-/blob/main/GenAi_RNN_One_Line.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import numpy as np

# Our sentence
sentence = "when will we eat the breakfast"

# Split sentence into words
words = sentence.split()

print(words)

['when', 'will', 'we', 'eat', 'the', 'breakfast']


In [3]:
vocab = sorted(set(words))

word_to_id = {word: i for i, word in enumerate(vocab)}
id_to_word = {i: word for word, i in word_to_id.items()}

print(word_to_id)

{'breakfast': 0, 'eat': 1, 'the': 2, 'we': 3, 'when': 4, 'will': 5}


In [4]:
X = []
y = []

for i in range(len(words) - 1):
    X.append([word_to_id[word] for word in words[:i+1]])
    y.append(word_to_id[words[i+1]])

print("X =", X)
print("y =", y)

X = [[4], [4, 5], [4, 5, 3], [4, 5, 3, 1], [4, 5, 3, 1, 2]]
y = [5, 3, 1, 2, 0]


In [5]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

X = pad_sequences(X, padding="pre")

X = np.array(X)
y = np.array(y)

print(X)
print(y)

[[0 0 0 0 4]
 [0 0 0 4 5]
 [0 0 4 5 3]
 [0 4 5 3 1]
 [4 5 3 1 2]]
[5 3 1 2 0]


In [6]:
model = tf.keras.Sequential([
    tf.keras.layers.Embedding(
        input_dim=len(vocab),
        output_dim=16
    ),

    tf.keras.layers.SimpleRNN(32),

    tf.keras.layers.Dense(len(vocab), activation="softmax")
])

model.compile(
    optimizer="adam",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [7]:
history = model.fit(
    X,
    y,
    epochs=500,
    verbose=0
)

print("Training complete!")

Training complete!


In [8]:
def predict_next_word(text):

    input_words = text.split()

    input_ids = [
        word_to_id[word]
        for word in input_words
        if word in word_to_id
    ]

    input_ids = pad_sequences(
        [input_ids],
        maxlen=X.shape[1],
        padding="pre"
    )

    prediction = model.predict(input_ids, verbose=0)

    predicted_id = np.argmax(prediction[0])

    return id_to_word[predicted_id]

In [9]:
print(predict_next_word("when"))

will


In [10]:
print(predict_next_word("when will"))

we
